version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      ENV: "dev"
      PORT: "8080"
      POSTGRES_HOST: "localhost"          
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "pergudanganmi"
      POSTGRES_PASSWORD: "pergudanganmi"
      POSTGRES_DATABASE: "pergudanganmi"
      REDIS_HOST: "redis"          
      REDIS_PORT: "6379"
      JWT_SECRET_KEY: "erwhdhsajdahjkdhqwiuou"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pergudanganmi
      - POSTGRES_PASSWORD=pergudanganmi
      - POSTGRES_DB=pergudanganmi
    ports:
      - "5432:5432"
